### ISSUE TITLE
Feature: CDN, Certificate manager, Provider folderId

### ISSUE THREAD

**Issue by dro-sh** [tagesjump/provider-upjet-yc#19]
I need CRD for Yandex Cloud CDN, Certificate manager. Why are not they in this provider? Is there any problem to generate for them resources from terraform files ([Certificate manager](https://registry.terraform.io/providers/yandex-cloud/yandex/latest/docs/resources/cm_certificate), [CDN](https://registry.terraform.io/providers/yandex-cloud/yandex/latest/docs/resources/cdn_resource)).

[Provider Config](https://github.com/yandex-cloud/crossplane-provider-yc/blob/main/examples/providerconfig/providerconfig.yaml) from Yandex Cloud has fields `cloudId`, `folderId`. Is it possible to do it the same way to use folderId from provider config and not set folderId for each resources?

**Comment by ssch1337** [comment]
In release 1.4.0 there are no plans to add a default folderId, I have allocated it to a separate issue #22
